import React, { useState } from 'react';
import HelpIcon from '@mui/icons-material/Help';
import './HelpButton.css';
import Modal from 'react-modal';

function HelpButton() {
  const [isOpen, setIsOpen] = useState(false);

  const toggleModal = () => {
    setIsOpen(!isOpen);
  };
  const closeModal = () => {
    setIsOpen(false);
  };
  return (
    <div>
      <button className="help-button" title='I dont get it!' onClick={toggleModal}>
        Help
        <HelpIcon/> 
      </button>

      {isOpen && (
        <Modal ariaHideApp={false} isOpen={isOpen} className="help-popup-modal" 
            overlayClassName="help-popup-overlay"
            onRequestClose={closeModal}>
          <div className="help-modal-content">
            <h1>Help</h1>

            <h2>Video Streamliner</h2>
            <p>The video stream is a feature that allows you to remove unwanted clips from your video. Simplify content down to the essential details. It's like having a personal assistant who sifts through your content and selects the most important segments.</p>

            <h2>Narration Improver</h2>
            <p>The narration Improver is a feature that allows you to remove unwanted audio from your video. EVA will enhance your audio quality by removing or smoothing out mumbles and ensuring a consistent tone throughout video. It's also equipped with an audio volume normalizer to provide a balanced audio experience for your viewers.</p>

            <h2>Focus group</h2>
            <p>The focus group is a feature that helps you get feedback as you work on editing your video. Helps you ensure your intended audience will stick with your video right to the end and walk away with the message you wanted to deliver. Gives feedback on factors such as Tone, Clarity and Engagement.</p>

            <h3>What do the colors mean?</h3>
            <p>Each color represents the tone of clip, focusing on what is being said, not how the speaker is saying it:</p>
            <ul style={{ display: 'flex',gap:"2%" }}>
                <li>
                    <span style={{ display: 'inline-block', width: '20px', height: '20px', backgroundColor: 'green', marginRight: '10px' }}></span>
                    Positive
                </li>
                <li>
                    <span style={{ display: 'inline-block', width: '20px', height: '20px', backgroundColor: 'red', marginRight: '10px' }}></span>
                    Negative
                </li>
                <li>
                    <span style={{ display: 'inline-block', width: '20px', height: '20px', backgroundColor: 'yellow', marginRight: '10px' }}></span>
                    Neutral
                </li>
            </ul>

            <h3>Chat bot</h3>
            <p>Chat bot lets you ask questions about video and can give instant feedback</p>

            <h2>How to use scrubber?</h2>
            <p>Scrubber is a tool that helps you to edit the video manually based off the output generated by feauteres.</p>
            <ul style={{ display: 'flex',gap:"2%" }}>
                <li>
                    <span style={{ display: 'inline-block', width: '20px', height: '20px', backgroundColor: '#cfb456', marginRight: '10px' }}></span>
                    Key clip
                </li>
                <li>
                    <span style={{ display: 'inline-block', width: '20px', height: '20px', backgroundColor: 'grey', marginRight: '10px' }}></span>
                    Removed Clip
                </li>
            </ul>
            <p><strong>Add Deleted Zone:</strong> You can add a deleted zone</p>
            <p><strong>Activate Restore Mode:</strong> You can add the clips directly from sidepanel.</p>
          </div>
          <button onClick={closeModal} style={{marginLeft:"30%"}}>Close</button>
        
        </Modal>
      )}
    </div>
  );
}

export default HelpButton;